-- Create Database
CREATE DATABASE IF NOT EXISTS stonecore_db;
USE stonecore_db;

-- Create products table
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `name_em` varchar(255) DEFAULT NULL,
  `category` varchar(100) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `original_price` decimal(10,2) DEFAULT NULL,
  `rating` decimal(2,1) DEFAULT '4.5',
  `reviews` int(11) DEFAULT '0',
  `description` text,
  `features` text,
  `details` text,
  `image` varchar(500) NOT NULL,
  `images` text,
  `in_stock` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Products (all 8 products from your JS array)
INSERT INTO `products` (`id`, `name`, `name_em`, `category`, `price`, `original_price`, `rating`, `reviews`, `description`, `features`, `details`, `image`, `images`, `in_stock`) VALUES
(1, 'Handcrafted Miniature Zen Garden Diorama', 'Zen Garden <em>Diorama</em>', 'Zen Stack', 1200.00, 1789.00, 4.8, 127, 'Bring peace and natural beauty into your space with this beautifully handcrafted miniature Zen garden. Designed with carefully selected natural stones, detailed bonsai-style trees, and a tiny wooden shrine, this piece captures the essence of a tranquil landscape in a compact form. The realistic textures, moss detailing, and layered stone steps add depth and authenticity, giving it a premium artistic feel. Every piece is handmade — no two are exactly the same.', '["Handcrafted with attention to detail","Natural river stones and textured elements","Miniature bonsai-style trees — realistic finish","Decorative wooden shrine centerpiece","Matte natural texture — premium look","Ideal for modern interiors and gifting"]', '{"Material":"Natural stones, resin, artificial bonsai","Size":"Approx. 15–25 cm","Finish":"Matte natural texture","Color Theme":"Earth tones — green, gray, beige","Weight":"Lightweight","Customizable":"Yes, on request"}', 'img/product/Handcrafted Miniature Zen Garden Diorama/Zen-Garden-Diorama1.jpeg', '["img/product/Handcrafted Miniature Zen Garden Diorama/Zen-Garden-Diorama1.jpeg","img/product/Handcrafted Miniature Zen Garden Diorama/Zen-Garden-Diorama2.jpeg","img/product/Handcrafted Miniature Zen Garden Diorama/Zen-Garden-Diorama3.jpeg","img/product/Handcrafted Miniature Zen Garden Diorama/Zen-Garden-Diorama4.jpeg"]', 1),

(2, 'Harmony Bridge Zen Garden', 'Harmony Bridge <em>Zen Garden</em>', 'Bridge Series', 899.00, 1145.00, 4.6, 89, 'Experience a blend of color, calm, and creativity with this handcrafted miniature Zen garden. The highlight is a beautifully crafted colorful wooden bridge, symbolizing connection and harmony within nature. Paired with layered stone steps, a monk figurine, dense bonsai canopy, and lush moss textures — the scene creates a serene environment that feels both artistic and meaningful.', '["Built with precision and care","Peaceful monk figurine — calm and mindfulness","Colorful wooden bridge — unique artistic highlight","Dense bonsai trees — natural and realistic","Layered stone details — adds depth and structure","Perfect for modern décor and gifting"]', '{"Material":"Natural stones, resin, bonsai, wood","Size":"Approx. 18–30 cm","Finish":"Matte natural texture","Color Theme":"Earth tones with vibrant bridge accents","Weight":"Lightweight yet stable","Customizable":"Yes, color theme on request"}', 'img/product/Harmony Bridge Zen Garden/Harmony Bridge Zen Garden1.png', '["img/product/Harmony Bridge Zen Garden/Harmony Bridge Zen Garden1.png","img/product/Harmony Bridge Zen Garden/Harmony Bridge Zen Garden2.png","img/product/Harmony Bridge Zen Garden/Harmony Bridge Zen Garden3.png","img/product/Harmony Bridge Zen Garden/Harmony Bridge Zen Garden4.png"]', 1),

(3, 'Serene Monk Bonsai Garden', 'Serene Monk <em>Bonsai Garden</em>', 'Monk Series', 700.00, 1230.00, 4.9, 203, 'A serene handcrafted monk bonsai garden with a meditating monk figurine surrounded by natural stones and bonsai branches. Featuring layered natural stone formations, realistic moss detailing, and carefully shaped miniature bonsai trees — the scene creates a tranquil landscape full of depth and character. The monk figurine sits peacefully at the center, adding a spiritual and mindful energy to any space.', '["Meditating monk figurine at center","Realistic moss and stone formations","Carefully shaped miniature bonsai trees","Spiritual and mindful energy","Perfect for meditation corners","Each unit individually handmade"]', '{"Material":"Natural stones, resin, bonsai, monk figurine","Size":"Approx. 15–25 cm","Finish":"Matte natural texture","Color Theme":"Earth tones — dark stone, green moss","Weight":"Lightweight","Customizable":"Yes, on request"}', 'img/product/Serene Monk Bonsai Garden/Harmony Bridge Zen Garden1.png', '["img/product/Serene Monk Bonsai Garden/Harmony Bridge Zen Garden1.png","img/product/Serene Monk Bonsai Garden/Harmony Bridge Zen Garden2.png","img/product/Serene Monk Bonsai Garden/Harmony Bridge Zen Garden3.png"]', 1),

(4, 'Stone Lantern Bonsai Retreat', 'Stone Lantern <em>Bonsai Retreat</em>', 'Bonsai Collection', 499.00, 999.00, 4.7, 156, 'A peaceful stone lantern retreat with miniature bonsai, natural slate stones, and a glowing lantern centerpiece. Two bonsai-style trees flank a detailed miniature red lantern shrine, surrounded by stacked natural river stones and soft moss textures. The tall standing stones create a dramatic backdrop while the layered base adds dimension and depth to the composition.', '["Twin bonsai trees flanking a red lantern shrine","Stacked natural river stones","Tall standing stones — dramatic backdrop","Soft moss textures throughout","Layered base for depth and dimension","Built with natural materials throughout"]', '{"Material":"River stones, slate, artificial moss, bonsai branches","Size":"Approx. 18–28 cm","Finish":"Matte natural texture","Color Theme":"Dark stone, red lantern accents, green moss","Weight":"Lightweight","Customizable":"Yes, on request"}', 'img/product/Stone Lantern Bonsai Retreat/Serene Monk Bonsai Garden1.png', '["img/product/Stone Lantern Bonsai Retreat/Serene Monk Bonsai Garden1.png","img/product/Stone Lantern Bonsai Retreat/Serene Monk Bonsai Garden2.png","img/product/Stone Lantern Bonsai Retreat/Serene Monk Bonsai Garden3.png","img/product/Stone Lantern Bonsai Retreat/Serene Monk Bonsai Garden4.png"]', 1),

(5, 'Whispering Bonsai Sanctuary', 'Whispering Bonsai <em>Sanctuary</em>', 'Bonsai Collection', 899.00, 1398.00, 4.8, 98, 'Step into a quiet world of nature and imagination with this handcrafted miniature Zen garden. A unique highlight is the elevated wooden perch holding a symbolic apple, adding a touch of storytelling and visual charm. The natural moss textures and carefully arranged stones create depth and realism, while the delicate tree branches form a peaceful canopy over the scene.', '["Intricate bonsai-style trees","Unique apple perch — storytelling element","Layered natural stone base","Natural moss textures — depth and realism","Handcrafted wooden platform","Truly one-of-a-kind design"]', '{"Material":"Natural stones, resin, bonsai, wood","Size":"Approx. 15–25 cm","Finish":"Matte natural look","Color Theme":"Dark stone tones, green moss, earthy accents","Weight":"Lightweight and durable","Customizable":"Yes, on request"}', 'img/product/Whispering Bonsai Sanctuary/Whispering Bonsai Sanctuary1.png', '["img/product/Whispering Bonsai Sanctuary/Whispering Bonsai Sanctuary1.png","img/product/Whispering Bonsai Sanctuary/Whispering Bonsai Sanctuary2.png","img/product/Whispering Bonsai Sanctuary/Whispering Bonsai Sanctuary3.png","img/product/Whispering Bonsai Sanctuary/Whispering Bonsai Sanctuary4.png"]', 1),

(6, 'Shizendo Monk Garden', 'Shizendo Monk <em>Garden</em>', 'Premium Zen Collection', 2499.00, 3599.00, 4.9, 88, 'Inspired by the tranquility of traditional Japanese \'Shizendo\' (Way of Nature) philosophy, this piece is a meticulously crafted world-in-miniature. Featuring layered, ancient-look natural river stones, lush preserved moss, two artisanal bonsai-style trees, and a symbolic red Torii-gate style shrine. At its heart sits our \'Serene Sage\' monk figure, sculpted in a deep meditative blue, embodying peace, wisdom, and inner harmony. Every element, from the miniature stone steps to the smooth, standing rocks, is placed with intention, creating a profound sense of natural balance and ancient calm.', '["Deeply meditative monk figure in cobalt blue — wisdom and harmony","Two premium, dense-foliage bonsai structures","Torii-gate style shrine with traditional red finish","Multi-layered river stone formation","Aged, preserved moss textures for timeless look","Unique artisan construction — no two pieces are identical"]', '{"Material":"Select river stones, slate bedrock base, preserved moss, wood shrine, sculpted polymer monk","Size":"Approx. 12–14 inches wide (slightly larger feel)","Finish":"Textured, weathered natural finish","Color Theme":"Deep earth tones, traditional red, rich cobalt blue, natural greens","Weight":"Solid, premium feel (approx. 2.5 lbs)","Customizable":"No, this is a fixed artisan piece"}', 'img/Product/Shizendo Monk Garden/Shizendo Monk Garden1.png', '["img/Product/Shizendo Monk Garden/Shizendo Monk Garden1.png","img/Product/Shizendo Monk Garden/Shizendo Monk Garden2.png","img/Product/Shizendo Monk Garden/Shizendo Monk Garden3.png","img/Product/Shizendo Monk Garden/Shizendo Monk Garden4.png","img/Product/Shizendo Monk Garden/Shizendo Monk Garden5.png"]', 1),

(7, 'Whispering Monk Zen Garden', 'Whispering Monk <em>Zen Garden</em>', 'Monk Series', 1799.00, 2299.00, 4.8, 67, 'A one-of-a-kind handmade decor piece inspired by traditional Japanese Zen landscapes. Carefully arranged using layered natural stones, moss details, two handcrafted bonsai-style trees, and a small red shrine. At the center sits a smiling monk figurine dressed in blue, symbolizing calm, joy, and inner balance. A small stone staircase leads toward the shrine, while smooth standing rocks and detailed greenery complete the natural look.', '["Smiling monk figurine in blue — joy and balance","Two handcrafted bonsai-style trees","Small red shrine centerpiece","Layered stone staircase detail","Natural river stones and moss","Every piece slightly different — truly handmade"]', '{"Material":"River stones, slate base, artificial moss, wood shrine","Size":"Approx. 10–12 inches wide","Finish":"Matte natural texture","Color Theme":"Earth tones, red shrine, green bonsai","Weight":"Lightweight","Customizable":"Yes, on request"}', 'img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden1.png', '["img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden1.png","img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden2.png","img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden3.png","img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden4.png","img/Product/Whispering Monk Zen Garden/Whispering Monk Zen Garden5.png"]', 1),

(8, 'Hand Rock Piece', 'Hand Rock <em>Piece</em>', 'Monk Series', 300.00, 2299.00, 4.5, 67, 'A one-of-a-kind handmade decor piece inspired by traditional Japanese Zen landscapes. Carefully arranged using layered natural stones, moss details, two handcrafted bonsai-style trees, and a small red shrine. At the center sits a smiling monk figurine dressed in blue, symbolizing calm, joy, and inner balance. A small stone staircase leads toward the shrine, while smooth standing rocks and detailed greenery complete the natural look.', '["Smiling monk figurine in blue — joy and balance","Two handcrafted bonsai-style trees","Small red shrine centerpiece","Layered stone staircase detail","Natural river stones and moss","Every piece slightly different — truly handmade"]', '{"Material":"River stones, slate base, artificial moss, wood shrine","Size":"Approx. 10–12 inches wide","Finish":"Matte natural texture","Color Theme":"Earth tones, red shrine, green bonsai","Weight":"Lightweight","Customizable":"Yes, on request"}', 'img/product/hand rock pieace/Hand made stone1.png', '["img/product/hand rock pieace/Hand made stone1.png","img/product/hand rock pieace/Hand made stone2.png","img/product/hand rock pieace/Hand made stone3.png"]', 1);